# Generated by Django 6.0.6 on 2026-06-23 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Penvarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="pens/")),
                ("dtae_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lg", "linc-glyser"),
                            ("bl", "Ball-pen"),
                            ("dm", "Doms"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
