# Generated by Django 6.0.6 on 2026-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="penvarity",
            name="company",
            field=models.TextField(default=""),
        ),
    ]
