# Generated by Django 6.0.6 on 2026-06-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pen", "0002_penvarity_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="penvarity",
            name="quantity",
            field=models.BigIntegerField(default=0),
        ),
    ]
