# Generated by Django 6.0.6 on 2026-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pen", "0003_penvarity_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penvarity",
            name="quantity",
            field=models.BigIntegerField(default=0),
        ),
    ]
