# Generated by Django 6.0.6 on 2026-06-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pen", "0005_alter_penvarity_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penvarity",
            name="quantity",
        ),
    ]
